//
// Created by Tanner on 10/22/2023.
//

#ifndef ESP32SPEAKERS_DEFINES_H
#define ESP32SPEAKERS_DEFINES_H

#endif //ESP32SPEAKERS_DEFINES_H

const float MAX_LINEAR_VOLUME = 30;
const float MIN_LINEAR_VOLUME = 1;
const float MAX_DB_VOLUME = 0.0;
const float MIN_DB_VOLUME = -30.0;


#define IR_RECEIVE_PIN 22
#define WEBSOCKET_PORT 5555
#define TIME_TOLERANCE 20
#define START_VOLUME 20
#define START_SUB_VOLUME 30
#define START_MUTE 0
#define START_SOURCE 0
#define DEBOUNCE_DELAY 30000





